<?php

  $apiKey="rzp_test_DGt7hUpgI9tVYp";

  include_once 'database.php';
  if(isset($_POST['save']))
 {  
     $fullname = $_POST['fullname'];
     $email= $_POST['email'];
     $phoneno = $_POST['phoneno'];
     $date = $_POST['date'];
     $paymentid = $_POST['paymentid'];
     $amount = $_POST['amount'];
     
     $sql = "INSERT INTO userinfo (fullname, email, phone, date, amount) VALUES ('$fullname', '$email', '$phoneno', '$date', '$amount')";
   
     
     if (mysqli_query($conn, $sql)){
        echo "Payment successfull";
    }
    else{
        echo "Error:" .$sql ."" .mysqli_error($conn);
    }
}mysqli_close($conn);                    


?>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>


<form action="payscript.php" method="POST">

<script
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="<?php echo $apiKey;?>" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
    data-amount="<?php echo $_POST['amount']*100;?>"// Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
    data-currency="INR"// You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-order_id="<?php echo $_POST['paymentid'];?>"// Replace with the order_id generated by you in the backend.
    data-buttontext="Pay with Razorpay"
    data-name="Angelic Deeds"
    data-description="NGO Charitable Cooperation"
    data-image="image/a1.jpg"
    data-prefill.name="<?php echo $_POST['fullname'];?>"
    data-prefill.email="<?php echo $_POST['email'];?>"
    data-prefill.contact="<?php echo $_POST['phoneno'];?>"
   
    data-theme.color="#F37254">
</script>
<input type="hidden" custom="Hidden Element" name="hidden">
</form>

<style>
    .razorpay-payment-button {display: none;}
</style>

<script type="text/javascript">
    $(document).ready(function(){

        $('.razorpay-payment-button').click();
    });
   

</script>